version: 0.2

phases:
    install:
        commands:
            - cd frontEnd
            - npm install
    build:
        commands:
            - npm run build

artifacts:
    files:
        - frontEnd/dist/**/*
        - frontEnd/dist/index.html
    base-directory: frontEnd/dist # Especifica la carpeta desde la que se recogerán los artefactos
    discard-paths: yes
