version: '3.7'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        networks:
            - backendnetwork
        environment:
            DB_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234567
            POSTGRES_DB: database_portf
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - '80:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
            PGADMIN_DEFAULT_PASSWORD: 1234567
        depends_on:
            - postgres
        networks:
            - backendnetwork

    backend-server:
        container_name: backend-server
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - '8000:8000'
        volumes:
            - backend-server-data:/app
        networks:
            - backendnetwork
        environment:
            DB_HOST: postgres

volumes:
    postgres-data:
    backend-server-data:

networks:
    backendnetwork:
# # Use postgres/example user/password credentials
# version: '3.8'

# services:
#     postgres:
#         image: postgres
#         restart: always
#         ports:
#             - '5432:5432'
#         environment:
#             DB_HOST: postgres
#             POSTGRES_USER: postgres
#             POSTGRES_PASSWORD: 1234567
#             POSTGRES_DB: database_portf
#         # volumes:
#         #     - ./data:/var/lib/postgresql/data

#     pgadmin:
#         image: dpage/pgadmin4
#         restart: always
#         ports:
#             - '80:80'
#         environment:
#             PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
#             PGADMIN_DEFAULT_PASSWORD: 1234567
#         depends_on:
#             - postgres

